FROM alpine:edge

RUN apk --update --no-cache add \
        erlang \
        erlang-ssl \
        erlang-asn1 \
        erlang-inets \
        erlang-xmerl \
        erlang-crypto \
        erlang-common-test \
        erlang-public-key
