FROM aialferov/pause

RUN apk --update add \
        bash \
        curl \
        drill \
        iperf3 \
        iproute2 \
        iptables \
        net-tools \
        socat \
        tcpdump && \
    rm -rf /var/cache/apk/*
